// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[] = "";

const char SSID[] = "";    // Network SSID (name) - change depending on the network
const char PASS[] = "";    // Network password (use for WPA, or use as key for WEP) - change depending on the network
const char DEVICE_KEY[] = "";    // Secret device password

void onLedDnevniChange();
void onLedKupatiloChange();
void onLedSpavacaChange();
void onLedTrpezarijaChange();
void onGarazaVrataChange();
void onZavjesaChange();
void onBezbjednosniSistemChange();
void onPorukeChange();

String poruke;
CloudDimmedLight led_dnevni;
CloudDimmedLight led_kupatilo;
CloudDimmedLight led_spavaca;
CloudDimmedLight led_trpezarija;
bool bezbjednosni_sistem;
bool garaza_vrata;
bool zavjesa;

void initProperties() {
    ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
    ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
    ArduinoCloud.addProperty(led_dnevni, READWRITE, ON_CHANGE, onLedDnevniChange);
    ArduinoCloud.addProperty(led_kupatilo, READWRITE, ON_CHANGE, onLedKupatiloChange);
    ArduinoCloud.addProperty(led_spavaca, READWRITE, ON_CHANGE, onLedSpavacaChange);
    ArduinoCloud.addProperty(led_trpezarija, READWRITE, ON_CHANGE, onLedTrpezarijaChange);
    ArduinoCloud.addProperty(garaza_vrata, READWRITE, ON_CHANGE, onGarazaVrataChange);
    ArduinoCloud.addProperty(zavjesa, READWRITE, ON_CHANGE, onZavjesaChange);
    ArduinoCloud.addProperty(bezbjednosni_sistem, READWRITE, ON_CHANGE, onBezbjednosniSistemChange);
    ArduinoCloud.addProperty(poruke, READWRITE, ON_CHANGE, onPorukeChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);